language: generic

branches:
  only:
    - master
    - develop

sudo: required

services:
  - docker

before_install:
  - docker pull base/archlinux

script:
  - scripts/travisDocker.sh

notifications:
  email:
    on_success: never
